version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nestjs_app_dev
    env_file:
      - .env.development
    ports:
      - "3000:3000" # Пробрасываем порт для доступа
    volumes:
      - .:/usr/src/app # Монтируем исходный код для автообновления
      - /usr/src/app/node_modules # Исключаем node_modules из монтирования
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db_dev
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: nestjs_dev_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
